#%RAML 1.0 Trait
usage: Apply this trait to enforce client-id identification
headers:
  client-id:
    type: string
    description: client id for authentication
    required: true
  client-secret:
    type: string
    description: client secret for authentication
    required: true 