#%RAML 1.0 Trait
usage: Apply this trait to enable consumers to supply trasaction id for end to end transaction tracking
headers:
  x-transaction-id:
    type: string
    description: transaction id for end to end tracking
    required: false